/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Twistko
 */
public class suhu extends javax.swing.JFrame {

    /**
     * Creates new form suhu
     */
    public suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroundTypeEditor1 = new usu.widget.PanelBackgroundTypeEditor();
        GrupSuhu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Celcius = new javax.swing.JRadioButton();
        Reamur = new javax.swing.JRadioButton();
        Kelvin = new javax.swing.JRadioButton();
        Fahrenheit = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        suhu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txC = new javax.swing.JTextField();
        txR = new javax.swing.JTextField();
        txF = new javax.swing.JTextField();
        txK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        Celcius.setBackground(new java.awt.Color(153, 255, 204));
        GrupSuhu.add(Celcius);
        Celcius.setText("Celcius");
        Celcius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CelciusMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CelciusMousePressed(evt);
            }
        });
        Celcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelciusActionPerformed(evt);
            }
        });

        Reamur.setBackground(new java.awt.Color(153, 255, 204));
        GrupSuhu.add(Reamur);
        Reamur.setText("Reamur");
        Reamur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReamurMousePressed(evt);
            }
        });
        Reamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReamurActionPerformed(evt);
            }
        });

        Kelvin.setBackground(new java.awt.Color(153, 255, 204));
        GrupSuhu.add(Kelvin);
        Kelvin.setText("Kelvin");
        Kelvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KelvinMousePressed(evt);
            }
        });
        Kelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelvinActionPerformed(evt);
            }
        });

        Fahrenheit.setBackground(new java.awt.Color(153, 255, 204));
        GrupSuhu.add(Fahrenheit);
        Fahrenheit.setText("Fahrenheit");
        Fahrenheit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FahrenheitMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Suhu awal");

        suhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Reamur)
                    .addComponent(Fahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(Kelvin)
                    .addComponent(Celcius)
                    .addComponent(suhu))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(Celcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reamur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fahrenheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kelvin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        txC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCActionPerformed(evt);
            }
        });

        txR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txRActionPerformed(evt);
            }
        });

        txF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFActionPerformed(evt);
            }
        });

        txK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hasil");

        jLabel3.setText("˚C");

        jLabel4.setText("˚R");

        jLabel5.setText("˚F");

        jLabel6.setText(" K");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(txF)
                            .addComponent(txR, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txC, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void KelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelvinActionPerformed

    private void ReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReamurActionPerformed

    private void CelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelciusActionPerformed

    private void txCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCActionPerformed

    private void txRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRActionPerformed

    private void txFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFActionPerformed

    private void txKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKActionPerformed

    private void CelciusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelciusMouseClicked
       /* double s,c,r,f,k;
        s = Float.parseFloat(suhu.getText());
        c = s;
        r = 4/5*c;
        f = (9/5*c) + 32;
        k = c + 273;
        
        txC.setText(String.valueOf(c));
        txR.setText(String.valueOf(r));
        txF.setText(String.valueOf(f));
        txK.setText(String.valueOf(k));*/
    }//GEN-LAST:event_CelciusMouseClicked

    public void print(double c, double r, double f, double k){
        txC.setText(String.format("%.2f",c));
        txR.setText(String.format("%.2f",r));
        txF.setText(String.format("%.2f",f));
        txK.setText(String.format("%.2f",k));
    }
    
    private void CelciusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelciusMousePressed
        double s=0,c,r,f,k;
        s = Double.parseDouble(suhu.getText());
        c = s;
        r = 0.8*s;
        f = 1.8*s+32;
        k = s+273;
        
        print(c,r,f,k);
    }//GEN-LAST:event_CelciusMousePressed

    private void ReamurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReamurMousePressed
        double s=0,c,r,f,k;
        s = Double.parseDouble(suhu.getText());
        r = s;
        c = 1.25*s;
        f = 2.25*s+32;
        k = c+273;
        
        print(c,r,f,k);
    }//GEN-LAST:event_ReamurMousePressed

    private void FahrenheitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FahrenheitMousePressed
        double s=0,c,r,f,k;
        s = Double.parseDouble(suhu.getText());
        f = s;
        c = (s-32)*5/9;
        r = (s-32)*4/9;
        k = c+273;
        
        print(c,r,f,k);
    }//GEN-LAST:event_FahrenheitMousePressed

    private void KelvinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KelvinMousePressed
        double s=0,c,r,f,k;
        s = Float.parseFloat(suhu.getText());
        k = s;
        c = s-273;
        f = 1.8*c+32;
        r = 0.8*c;
        
        print(c,r,f,k);
    }//GEN-LAST:event_KelvinMousePressed

    private void suhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Celcius;
    private javax.swing.JRadioButton Fahrenheit;
    private javax.swing.ButtonGroup GrupSuhu;
    private javax.swing.JRadioButton Kelvin;
    private javax.swing.JRadioButton Reamur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private usu.widget.PanelBackgroundTypeEditor panelBackgroundTypeEditor1;
    private javax.swing.JTextField suhu;
    private javax.swing.JTextField txC;
    private javax.swing.JTextField txF;
    private javax.swing.JTextField txK;
    private javax.swing.JTextField txR;
    // End of variables declaration//GEN-END:variables
}
